sudo: required

dist: trusty

language: node_js

node_js:
  - node

branches:
  only:
  - 2.0.0-beta.x

install: 
  - npm cache clean --force
  - npm install

script:
  - npm run build

before_deploy: 
  - |
    function npm_dist_tag() {
      if [[ "$TRAVIS_TAG" = *"-beta.x"* ]]; then
        echo "beta"
      else
        echo "latest"
      fi
    }
  - npm run bundle && cd dist

deploy:
  provider: npm
  email: aelbore.sg@gmail.com
  skip_cleanup: true
  tag: $(npm_dist_tag)
  api_key:
    secure: $NPM_TOKEN
  on:
    all_branches: true
    tags: true
    repo: ngx-devtools/task

after_deploy: |
  if [ "$(npm_dist_tag)" == "beta" ]; then
    echo "Hey"
  fi
