sudo: required

dist: trusty

language: node_js

node_js:
  - node

branches:
  only:
  - 2.0.0-beta.x

install: 
  - npm cache clean --force
  - npm install

script:
  - npm run build

after_success:
  - | 
    function npm_dist_tag() {
      if [[ "$TRAVIS_TAG" = *"-beta.x"* ]]; then
        echo "next"
      else
        echo "latest"
      fi
    }
  - $(npm_dist_tag)
