sudo: required

dist: trusty

language: node_js

node_js:
  - node

branches:
  only:
  - 2.0.0-beta.x

install: 
  - npm cache clean --force
  - npm install

script:
  - npm run build

after_success:
  - echo "$TRAVIS_TAG"

